accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'accounts'

urlpatterns = [
    path('login/',  auth_views.LoginView.as_view(template_name="accounts/login.html"),name='login'),
    path('signup/', views.signup, name='signup'),
    path('profile/',views.profile,name='profile'),
    path('logout/',  auth_views.LogoutView.as_view(),name='logout'),
    path('fav/',  auth_views.LogoutView.as_view(),name='fav'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path,include
from django.contrib.auth import views as auth_views
from . import views
from django.conf import settings
from django.conf.urls.static import static
# from accounts import views

urlpatterns = [
    path('admin/', admin.site.urls),
    #path('',  auth_views.LoginView.as_view(template_name="accounts/login.html"),name='login'),
    path('', views.TestPage.as_view(), name="test"),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include("accounts.urls", namespace="accounts")),
    path('',include('newspapers.urls', namespace="newspapers")),
    path('',include('rates.urls', namespace="rates")),
    #path('test/', views.TestPage.as_view(), name="test"),
    #path('newsletter/',include('newsletter.urls', namespace="newsletter")),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,document_root = settings.STATIC_ROOT)
if settings.DEBUG is True:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

rates/urls.py
from django.urls import path
from . import views
from django.conf.urls.static import static
from django.conf import settings
app_name='rates'

urlpatterns = [
	        path('news_ratess/<int:pk>/', views.news_ratess, name="news_ratess"),
	        path('news_rates/', views.news_rates, name="news_rates"),
	        path('city_rates/', views.city_rates, name="city_rates"),
	        path('paper_rates/<int:pk>/', views.paper_rates, name="paper_rates"),
	        path('calc/', views.calc, name="calc"),
            
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

accounts/models.py
from django.conf import settings
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
from newspapers.models import Newspaper_name,Preference

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete="models.CASCADE")
    name = models.CharField(max_length=30, blank=True)
    email_id = models.EmailField(max_length=70,blank=True, null= True, unique= True)
    #bio = models.TextField(max_length=500, blank=True)
    phone_number = models.IntegerField(blank=True ,null=True)
    birth_date = models.DateField(null=True, blank=True)
    service_number = models.IntegerField(blank=True ,null=True)
    designation = models.CharField(max_length=30, blank=True)
    railway_zone = models.CharField(max_length=30, blank=True)
    
    picture = models.ImageField(upload_to = 'profile_pics')
    SEX_CHOICES = (
        ('F', 'Female',),
        ('M', 'Male',),
        ('U', 'Unsure',),
    )
    sex = models.CharField(
        max_length=1,
        choices=SEX_CHOICES,
    )
    def __str__(self):
        return self.user.username


@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)

@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    instance.profile.save()

class Favourites(models.Model):
    user=models.OneToOneField(User, on_delete=models.CASCADE)
    newspaper_name=models.OneToOneField(Newspaper_name, on_delete=models.CASCADE)

accounts/forms.py
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from django import forms
from accounts.models import Profile

class UserForm(forms.ModelForm):
    username = forms.IntegerField(widget= forms.TextInput
                           (attrs={'placeholder':'Enter RUID'}))
    email = forms.EmailField(widget= forms.TextInput
                           (attrs={'placeholder':'Enter email'}))
    password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Enter Password'}))
    class Meta:
        model = User
        fields = ("username", "email", "password")
    def save (self):
        password = self.cleaned_data.pop('password')
        u = super().save()
        u.set_password(password)
        u.save()
        return u

class ProfileForm(forms.ModelForm):
    picture = forms.ImageField(required = False)
    name =  forms.CharField(widget= forms.TextInput
                           (attrs={'placeholder':'Enter Name'}))
    email_id = forms.EmailField(widget= forms.TextInput
                           (attrs={'placeholder':'Enter another email'}))
    phone_number = forms.IntegerField(widget= forms.TextInput
                           (attrs={'placeholder':'Enter Mobile Number'}))
    birth_date = forms.DateField(widget= forms.TextInput
                           (attrs={'placeholder':'Date of Birth'}))
    service_number = forms.IntegerField(widget= forms.TextInput
                           (attrs={'placeholder':'Enter Service Number'}))
    designation = forms.CharField(widget= forms.TextInput
                           (attrs={'placeholder':'Enter Designation'}))
    railway_zone = forms.CharField(widget= forms.TextInput
                           (attrs={'placeholder':'Railway Zone'}))

    class Meta:
        model = Profile
        fields = ('name', 'email_id', 'phone_number','birth_date','service_number','designation','railway_zone','sex','picture')

accounts/views.py


# Create your views here.
from django.contrib.auth.forms import UserCreationForm
from django.urls import reverse_lazy
from django.views import generic
from django.contrib import messages
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from accounts.forms import UserForm,ProfileForm
from . import models
from django.views.generic import TemplateView,ListView,DetailView
from django.db import  transaction
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from mysite import urls
from . import models
import time


def LogInView(request):
    if request.method == "POST":
        username=request.POST.get('username')
        password=request.POST.get('password')
        email=request.POST.get('email')
        user=authenticate(username=username,password=password)
        if user:
            if user.is_active:
                login(request,user)
                # return render(request,'classroom/questions.html')
                # return redirect(classroom.views.question)
                return HttpResponseRedirect('/')
            else:
                content_dic={'error':'You are a Inactive User Contact Admin'}
                return render(request,'accounts/login.html',context=content_dic)
        else:
            content_dic={'error':'Invalid Roll Number or Password'}
            return render(request,'accounts/login.html',context=content_dic)
    else:
        return render(request,'accounts/login.html')

# def logout_user(request):
#     logout(request)
#     messages.success(request,('You have been Logged out.'))
#     return redirect('fav')

@transaction.atomic
def signup(request):

    if request.method == 'POST':
        user_form = UserForm(request.POST)
        profile_form = ProfileForm(request.POST)

        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            user.refresh_from_db()
            profile_form.full_clean()
            profile_form = ProfileForm(request.POST, instance=user.profile)
            profile_form.save()
            return redirect('login')


    else:
        user_form = UserForm()
        profile_form = ProfileForm()

    return render(request, 'accounts/signup.html', {
        'user_form': user_form,
        'profile_form': profile_form

    })


@login_required
@transaction.atomic
def update_profile(request):
    if request.method == 'POST':
        user_form = UserForm(request.POST, instance=request.user)
        profile_form = ProfileForm(request.POST, instance=request.user.profile)
        if user_form.is_valid() and profile_form.is_valid():
            user_form.save()
            profile_form.save()
            messages.success(request, _('Your profile was successfully updated!'))
            return HttpResponseRedirect('/accounts/login/')
        else:
            messages.error(request, _('Please correct the error below.'))
    else:
        user_form = UserForm(instance=request.user)
        profile_form = ProfileForm(instance=request.user.profile)
    return render(request, 'accounts/signup.html', {
        'user_form': user_form,
        'profile_form': profile_form
    })


def profile (request):
    return render(request,'accounts/profile.html' , {'user' : request.user})

accounts/templates/accounts/login0.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<title></title>
	<script src="{% static 'lib/jquery-3.3.1.min.js' %}"></script>
    <link rel="stylesheet" href="{% static 'lib/bootstrap4.min.css' %}">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css">
    <link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
</head>
<body>
    <div id="hero" class="row">
        <div id="hero-overlay"></div>
        <div class="col-lg-3 mx-auto my-5" id="login-box">
        	<div class="m-auto text-center bg-info p-3 text-white rounded">Login To Your Account</div>
        	<form method="POST"  class="form-group mx-auto" style="background: rgba(0, 0, 0, 0.9);">
        		{% csrf_token %}
        		<br>
        		<center><img src="{% static 'img/indian_railway.png' %}" class="rounded-circle img-fluid" width="150"></center>
        		<br>
        		<div class="col-11 mx-auto form-group input-group">
	              <div class="input-group-prepend">
	                <span class="input-group-text"><i class="fa fa-fingerprint"></i></span>
	              </div>
	              <input type="text" name="login_uid" class="form-control" placeholder="Enter R UID" required>
	            </div>
        		<div class="col-11 mx-auto form-group input-group">
	              <div class="input-group-prepend">
	                <span class="input-group-text"><i class="fa fa-envelope"></i></span>
	              </div>
	              <input type="email" name="login_email" class="form-control" placeholder="Enter Email" required>
	            </div>
	            <div class="col-11 mx-auto form-group input-group">
	              <div class="input-group-prepend">
	                <span class="input-group-text"><i class="fa fa-key"></i></span>
	              </div>
	              <input type="Password" name="login_password" class="form-control" placeholder="Enter Password" required>
	            </div>
	            <div class="col-11 mx-auto form-group input-group text-white"><input type="checkbox" name="">&nbsp; Remember Me</div>
	            <center><button type="submit" class="btn btn-primary text-center my-2">Login <i class="far fa-paper-plane"></i></button></center>
	            <div class="text-center text-white"><a href="#">Forgot Password</a><br>Not Registered ? <a href="{% url 'accounts:signup' %}" onclick="change();">SignUp Here</a> </div><br>
        	</form>
        </div>
        <!--
        <div class="col-lg-5 mx-auto my-5" id="signup-box">
        	<div class="m-auto text-center bg-info p-3 text-white rounded">Register New Account</div>
        	<form method="POST" action="/destination-url/" class="form-group mx-auto" style="background: rgba(0, 0, 0, 0.9);">
        		<center><img src="img/avatar.png" class="img-fluid py-3"></center>
        		<div class="row pt-3 mx-auto pt-3">
	        		<div class="col-6 mx-auto form-group input-group">
		              <div class="input-group-prepend">
		                <span class="input-group-text"><i class="fas fa-file-signature"></i></span>
		              </div>
		              <input type="text" name="signup_name" class="form-control" placeholder="Enter Full Name" required>
		            </div>
	        		<div class="col-6 mx-auto form-group input-group">
		              <div class="input-group-prepend">
		                <span class="input-group-text"><i class="fa fa-envelope"></i></span>
		              </div>
		              <input type="email" name="signup_email" class="form-control" placeholder="Enter Email" required>
		            </div>
		        </div>
		        <div class="row pt-3 mx-auto">
	        		<div class="col-6 mx-auto form-group input-group">
		              <div class="input-group-prepend">
		                <span class="input-group-text"><i class="fa fa-fingerprint"></i></span>
		              </div>
		              <input type="text" name="signup_uid" class="form-control" placeholder="Enter R UID" required>
		            </div>
	        		<div class="col-6 mx-auto form-group input-group">
		              <div class="input-group-prepend">
		                <span class="input-group-text"><i class="fab fa-servicestack"></i></span>
		              </div>
		              <input type="text" name="signup_snumber" class="form-control" placeholder="Service Number" required>
		            </div>
		        </div>
		        <div class="row pt-3 mx-auto">
	        		<div class="col-6 mx-auto form-group input-group">
		              <div class="input-group-prepend">
		                <span class="input-group-text"><i class="fas fa-phone"></i></span>
		              </div>
		              <input type="number" name="signup_pnumber" class="form-control" placeholder="Enter Phone Number" required>
		            </div>
	        		<div class="col-6 mx-auto form-group input-group">
		              <div class="input-group-prepend">
		                <span class="input-group-text"><i class="fa fa-key"></i></span>
		              </div>
		              <input type="password" name="signup_password" class="form-control" placeholder="Enter New Password" required>
		            </div>
		        </div>
		        <div class="row pt-3 mx-auto">
	        		<div class="col-6 mx-auto form-group input-group">
		              <div class="input-group-prepend">
		                <span class="input-group-text"><i class="far fa-calendar-alt"></i></span>
		              </div>
		              <input type="date" name="signup_dob" class="form-control" placeholder="Enter DOB" required>
		            </div>
	        		<div class="col-6 mx-auto form-group input-group">
		              <div class="input-group-prepend">
		                <span class="input-group-text"><i class="fa fa-mars-double"></i></span>
		              </div>
		              <select class="form-control" name="signup_gender">
		              	<option>Select Gender</option>
		              	<option>Male</option>
		              	<option>Female</option>
		              </select>
		            </div>
		        </div>	
	            
	            <center><button type="submit" class="btn btn-primary text-center my-2">Signup <i class="far fa-paper-plane"></i></button></center>
	            <div class="text-center text-white">Already Registered ? <a href="#" onclick="change();">Login Here</a> </div><br>
        	</form>
        </div>
    -->
    </div>
</body>
</html>

<script type="text/javascript">

	$('#signup-box').hide();

	function change(){
        $('#login-box').toggle();
        $('#signup-box').toggle();
    }
</script>

accounts/templates/accounts/login00.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<title></title>
	<script src="{% static 'lib/jquery-3.3.1.min.js' %}"></script>
    <link rel="stylesheet" href="{% static 'lib/bootstrap4.min.css' %}">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css">
    <link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
</head>
<body>
    <div id="hero" class="row">
        <div id="hero-overlay"></div>
        <div class="col-lg-3 mx-auto my-5" id="login-box">
        	<div class="m-auto text-center bg-info p-3 text-white rounded">Login To Your Account</div>
        	<form method="POST" action="{% url 'accounts:profile' %}" class="form-group mx-auto" style="background: rgba(0, 0, 0, 0.9);">
        		{% csrf_token %}
        		<br>
        		<center><img src="{% static 'img/indian_railway.png' %}" class="rounded-circle img-fluid" width="150"></center>
        		<br>
        		<div class="col-11 mx-auto form-group input-group">
	              <div class="input-group-prepend">
	                <span class="input-group-text"><i class="fa fa-fingerprint"></i></span>
	              </div>
	              <input type="text" name="username" id='username' class="form-control" placeholder="Enter R UID" required>
	            </div>
        		<div class="col-11 mx-auto form-group input-group">
	              <div class="input-group-prepend">
	                <span class="input-group-text"><i class="fa fa-envelope"></i></span>
	              </div>
	             <input type="email" name="email" id='email' class="form-control" placeholder="Enter Email" required>
	            </div>
	            <div class="col-11 mx-auto form-group input-group">
	              <div class="input-group-prepend">
	                <span class="input-group-text"><i class="fa fa-key"></i></span>
	              </div>
	               <input type="Password" name="password" id='password' class="form-control" placeholder="Enter Password" required>
	            </div>
	            <div class="col-11 mx-auto form-group input-group text-white"><input type="checkbox" name="">&nbsp; Remember Me</div>
	            <center><button type="submit" class="btn btn-primary text-center my-2">Login <i class="far fa-paper-plane"></i></button></center>
	            <div class="text-center text-white"><a href="#">Forgot Password</a><br>Not Registered ? <a href="{% url 'accounts:signup' %}" onclick="change();">SignUp Here</a> </div><br>
        	</form>
        </div>
        <!--
        <div class="col-lg-5 mx-auto my-5" id="signup-box">
        	<div class="m-auto text-center bg-info p-3 text-white rounded">Register New Account</div>
        	<form method="POST" action="/destination-url/" class="form-group mx-auto" style="background: rgba(0, 0, 0, 0.9);">
        		<center><img src="img/avatar.png" class="img-fluid py-3"></center>
        		<div class="row pt-3 mx-auto pt-3">
	        		<div class="col-6 mx-auto form-group input-group">
		              <div class="input-group-prepend">
		                <span class="input-group-text"><i class="fas fa-file-signature"></i></span>
		              </div>
		              <input type="text" name="signup_name" class="form-control" placeholder="Enter Full Name" required>
		            </div>
	        		<div class="col-6 mx-auto form-group input-group">
		              <div class="input-group-prepend">
		                <span class="input-group-text"><i class="fa fa-envelope"></i></span>
		              </div>
		              <input type="email" name="signup_email" class="form-control" placeholder="Enter Email" required>
		            </div>
		        </div>
		        <div class="row pt-3 mx-auto">
	        		<div class="col-6 mx-auto form-group input-group">
		              <div class="input-group-prepend">
		                <span class="input-group-text"><i class="fa fa-fingerprint"></i></span>
		              </div>
		              <input type="text" name="signup_uid" class="form-control" placeholder="Enter R UID" required>
		            </div>
	        		<div class="col-6 mx-auto form-group input-group">
		              <div class="input-group-prepend">
		                <span class="input-group-text"><i class="fab fa-servicestack"></i></span>
		              </div>
		              <input type="text" name="signup_snumber" class="form-control" placeholder="Service Number" required>
		            </div>
		        </div>
		        <div class="row pt-3 mx-auto">
	        		<div class="col-6 mx-auto form-group input-group">
		              <div class="input-group-prepend">
		                <span class="input-group-text"><i class="fas fa-phone"></i></span>
		              </div>
		              <input type="number" name="signup_pnumber" class="form-control" placeholder="Enter Phone Number" required>
		            </div>
	        		<div class="col-6 mx-auto form-group input-group">
		              <div class="input-group-prepend">
		                <span class="input-group-text"><i class="fa fa-key"></i></span>
		              </div>
		              <input type="password" name="signup_password" class="form-control" placeholder="Enter New Password" required>
		            </div>
		        </div>
		        <div class="row pt-3 mx-auto">
	        		<div class="col-6 mx-auto form-group input-group">
		              <div class="input-group-prepend">
		                <span class="input-group-text"><i class="far fa-calendar-alt"></i></span>
		              </div>
		              <input type="date" name="signup_dob" class="form-control" placeholder="Enter DOB" required>
		            </div>
	        		<div class="col-6 mx-auto form-group input-group">
		              <div class="input-group-prepend">
		                <span class="input-group-text"><i class="fa fa-mars-double"></i></span>
		              </div>
		              <select class="form-control" name="signup_gender">
		              	<option>Select Gender</option>
		              	<option>Male</option>
		              	<option>Female</option>
		              </select>
		            </div>
		        </div>	
	            
	            <center><button type="submit" class="btn btn-primary text-center my-2">Signup <i class="far fa-paper-plane"></i></button></center>
	            <div class="text-center text-white">Already Registered ? <a href="#" onclick="change();">Login Here</a> </div><br>
        	</form>
        </div>
    -->
    </div>
</body>
</html>

<script type="text/javascript">

	$('#signup-box').hide();

	function change(){
        $('#login-box').toggle();
        $('#signup-box').toggle();
    }
</script>

accounts/templates/accounts/profile.html
{% extends "main.html" %}

{% block content %}
    <div class="container bg-dark text-white" >

        <div class="container row rounded">
            <div class="col-lg-5 mt-5 ">
                <div class="col-7 mx-auto"><img src="{{ user.profile.picture.url}}"  class="img-fluid" width="350"></div>
            </div>
            <div class="col-lg-7 mt-5">
                <div class="col-lg-10 mx-auto">
                    <table class="table table-sm table-borderless table-hover ">
                        <tr><td>Name :</td><td>{{user.profile.name}}</td></tr>
                        <tr><td>Gender :</td><td>{{user.profile.sex}}</td></tr>
                        <tr><td>Email :</td><td>{{user.email}}</td></tr>
                        <tr><td>Registered UID :</td><td>{{user.username}}</td></tr>
                        <tr><td>Service Number :</td><td>{{user.profile.service_number}}</td></tr>
                        <tr><td>Phone Number :</td><td>{{user.profile.phone_number}}</td></tr>
                        <tr><td>Date Of Birth :</td><td>{{user.profile.birth_date}}</td></tr>
                    </table>
                </div>
            </div>
        </div>
        <div class="container row mx-auto">
            <div class="col-12 mt-5 border rounded">
                <h3 class="text-center d-block my-3">About User</h3>
            </div>
            <div class="col-12 mt-2 text-justify border rounded">
                <h3 class="ml-1 d-block my-3">Heading 1</h3>
                <P class="container">Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.</P>
            </div>
            <div class="col-12 mt-2 text-justify border rounded">
                <h3 class="ml-1 d-block my-3">Heading 2</h3>
                <P class="container">Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.</P>
            </div>
        </div>

    </div>
    {% endblock %}
</body>

</html>

accounts/templates/accounts/profile00.html
{% extends "main.html" %}

{% block content %}
    <div class="container bg-dark text-white" >

        <div class="container row rounded">
            <div class="col-lg-5 mt-5 ">
                <div class="col-7 mx-auto"><img src="{{ user.profile.picture.url}}"  class="img-fluid" width="350"></div>
            </div>
            <div class="col-lg-7 mt-5">
                <div class="col-lg-10 mx-auto">
                    <table class="table table-sm table-borderless table-hover ">
                        <tr><td>Name :</td><td>{{user.profile.name}}</td></tr>
                        <tr><td>Gender :</td><td>{{user.profile.sex}}</td></tr>
                        <tr><td>Email :</td><td>{{user.email}}</td></tr>
                        <tr><td>Registered UID :</td><td>{{user.username}}</td></tr>
                        <tr><td>Service Number :</td><td>{{user.profile.service_number}}</td></tr>
                        <tr><td>Phone Number :</td><td>{{user.profile.phone_number}}</td></tr>
                        <tr><td>Date Of Birth :</td><td>{{user.profile.birth_date}}</td></tr>
                    </table>
                </div>
            </div>
        </div>
        <div class="container row mx-auto">
            <div class="col-12 mt-5 border rounded">
                <h3 class="text-center d-block my-3">About User</h3>
            </div>
            <div class="col-12 mt-2 text-justify border rounded">
                <h3 class="ml-1 d-block my-3">Heading 1</h3>
                <P class="container">Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.</P>
            </div>
            <div class="col-12 mt-2 text-justify border rounded">
                <h3 class="ml-1 d-block my-3">Heading 2</h3>
                <P class="container">Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.</P>
            </div>
        </div>

    </div>
    {% endblock %}
</body>

</html>

accounts/templates/accounts/profile000.html
{% load static %}
<!DOCTYPE html>

<html lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <title>Bootsrap Practical</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" type="text/css" href="{% static 'lib/bootstrap4.min.css' %}" />
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.13/css/all.css">
    <script src="{% static 'lib/jquery-3.3.1.min.js' %}"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js"></script>
    <script src="{% static 'lib/bootstrap.min.js' %}"></script>
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    <style type="text/css">
        .table-borderless td, .table-borderless th {
            border: 0;
        }
    </style>
</head>

<body style="background-color: #6a963c;">
    <div class="container bg-dark text-white" >

        <div class="container row rounded">
            
            <div class="col-lg-7 mt-5">
                <div class="col-lg-10 mx-auto">
                    <table class="table table-sm table-borderless table-hover ">
                        <tr><td>Name :</td><td>{{user.profile.name}}</td></tr>
                        <tr><td>Gender :</td><td>{{user.profile.sex}}</td></tr>
                        <tr><td>Email :</td><td>{{user.email}}</td></tr>
                        <tr><td>Registered UID :</td><td>{{user.username}}</td></tr>
                        <tr><td>Service Number :</td><td>{{user.profile.service_number}}</td></tr>
                        <tr><td>Phone Number :</td><td>{{user.profile.phone_number}}</td></tr>
                        <tr><td>Date Of Birth :</td><td>{{user.profile.birth_date}}</td></tr>
                    </table>
                </div>
            </div>
        </div>
        <div class="container row mx-auto">
            <div class="col-12 mt-5 border rounded">
                <h3 class="text-center d-block my-3">About User</h3>
            </div>
            <div class="col-12 mt-2 text-justify border rounded">
                <h3 class="ml-1 d-block my-3">Heading 1</h3>
                <P class="container">Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.</P>
            </div>
            <div class="col-12 mt-2 text-justify border rounded">
                <h3 class="ml-1 d-block my-3">Heading 2</h3>
                <P class="container">Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.</P>
            </div>
        </div>

    </div>

</body>

</html>